---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      containers:
      - name: application
        image: ashvinbambhaniya/go-server:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000